---
firewall_state: started
firewall_enabled_at_boot: true

firewall_allowed_udp_ports:
  - "123"
  - "53"

firewall_allowed_tcp_ports:
  - "53"

firewall_additional_rules:
  # SSH
  - "iptables -A INPUT -p tcp --dport 22 -s 10.3.0.0/0 -j ACCEPT"
  - "iptables -A INPUT -p tcp --dport 22 -s 10.11.0.0/0 -j ACCEPT"

  # SNMP
  - "iptables -A INPUT -p udp --dport 161 -s 10.3.0.0/16 -j ACCEPT"
  - "iptables -A INPUT -p udp --dport 161 -s 10.11.0.0/16 -j ACCEPT"
