users:
  - username: josh
    name: Josh Preston
    groups: ['ops', 'docker']
    home: /home/josh
    password: "{{ secrets.users.josh.unix_shadow_hash }}"
    ssh_key:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEA+NAatW7Fn47StI5JjSGmiA9Rje910v+ZftAlY+djkdk9ZeCgM6JjqJQA7gtYIgCv7BA4qADNBWbmbA3jtT6fWEuxpppvmtfXT7kqWDkUeOBawtq0i5YJTo7WszY2N5DLjoaGdyB/aMIAOnJyfBzrCY/iYq7bzF0isCJnAjID6Cs= josh"
      - "ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAEX+XstpIlrgBTH96BvkiQF6tY6rQP0cWnzyOugB5KF/PtUM51c6x15xCaMIOw1PmjUVguNPxDrnUPdbYth/e3yDABvJPEKosYucRGkzGemfv0CptzYCEUUEm2WeKr8U1y1AL2gNqbhfXUAA1CbirMGo2PLo9pItLHOZeIKYrSxQU5Kjw== josh@sys12-mac.local"
      - "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBLYb2B4Kj/eioevUM1lqis/vpamjGOc77pfMVzEo79gslrfvfkhE40ESRHkoG+B35Z0lv8P/9fyHX7zw7Swnwk= josh@josh-Latitude-5501"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ5HRKieCuS1gm+AgGAr3SD9NrlBD2OrxxxQFf3bFXEK SSH Keypair for UCSB/LIB"

  - username: mokuno
    name: Mark Okuno
    groups: ['ops']
    home: /home/mokuno
    password: "{{ secrets.users.mokuno.unix_shadow_hash }}"
    ssh_key:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAwwI1LK0jmQYi6jynIZqhMF6yJ7T7iozwz7+zwbQ8l0dZ/Vwsea++x78ikLuFKqguMGNWcipSXakAB3UceGCFYdUE9LZ3h0dLp4AD/nalk5IJoyOkB8amachGunOWiuPIjC57I2ujEQJmSzue8jRyw0+eYBosHqt+kZuSjZEGkQbFdfwe9302OZ/QgjvBNNUWwSlSR95aFfFIAkIEPGKj4cvN7BF+NcF/YqP65sRnRGkgzjGZCQD4SBfz9PUu2oWdjk2HbAmjV/kFIe/WlIUzXmCKPSZYOYjR/zT3bS9QEFUE14ZiYKufqABZG1Aldbt8NeynM2t8xwKBwX2tgiuBdQ=="
    
  - username: logicmonitor
    name: LogicMonitor BotNet
    home: /home/logicmonitor
    shell: /bin/bash
    password: "{{ secrets.users.logicmonitor.unix_shadow_hash }}"
    ssh_key:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDc97wY2Hoprkmtf3PVOIP5CbGCqDM21O6pBfhw1Zz21bHoXWs0ftMc2/2tyTOiFBHrUvUGGunXVmB3o/HZaMof+P1rAjZMV/+BEB/kfjSeUtDu+p/iiVZ7QjW2PX8pMtAEZDd+ZhRndomP5xHGvb/0tne3Lz+o0owsbKXj7grhYiHXCcJYiohmudvkEGF70WjRQ1LYTwYejgH47V19yzsNyi0M4965lpdbpFWl9WN+9C9vASN70wqL+7+LkDVm714J7MEoluRaUSVbpfAw2scPmOhGW9MmZuu0W1M1ig5xSLYhgpbW8dYPFz9JGdO4RCr3abu4ZFNfSmYnKCiOrjhz"

  - username: ansible-deploy
    name: ansible-deploy
    home: /home/ansible-deploy
    shell: /bin/bash
    groups:
      - 'ansible-deploy'
    password: "{{ secrets.users.ansible_deploy.unix_shadow_hash }}"
    ssh_key:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHvp/st8Hp9MFNdCjWvHu4eplfrVX+p6vIJfI3hcWdh76VTOpZeNlwFFNwtlqHtKi9jjnagMQx4yVkA99lFm00xFK8cFRk4Ki1vzXCt42BEHLrYoFMDHizE+TvQTmZh/wPc3xTFrOLv5xoFBMD+jZlc6Z70lPqqwGWKCTPJUC+HStqxhXtX9BLVs17SYFTijo/EyW5MZh7mSeK/62oo8HcYDzRTzMm6FAJxbwUzpVsuG2ErojvNxsuVrphiXRNlN54JFEzukx81vsA+u3Bb/TW9zzMkY0FDrf1Jx5cldNhV+llOKFouerOI3xNQokouf1gNWxOejuUAWoNHZKQRqJH"

groups_to_create:
  - name: ops
